prometheus/config/file.sls, prometheus/osfamilymap.yaml
PR adding basic package & group handling (see https://github.com/saltstack/salt/issues/53325) on MacOS.
=> feat(macos): basic package and group handling

docs/TOFS_pattern.rst, prometheus/libtofs.jinja
* Automated using `ssf-formula` (v0.1.0-rc.2)
=> chore: use `semantic-release` cross-formula standard structure

.travis.yml, .yamllint, pillar.example, prometheus/defaults.yaml, prometheus/map.jinja, prometheus/osfamilymap.yaml, test/integration/default/inspec.yml
* Semi-automated using `ssf-formula` (v0.5.0)
* Fix errors shown below:
```bash
prometheus-formula$ $(grep "\- yamllint" .travis.yml | sed -e "s:^\s\+-\s\(.*\):\1:")
./prometheus/osfamilymap.yaml
1:89      error    line too long (116 > 88 characters)  (line-length)
1:24      error    trailing spaces  (trailing-spaces)
13:2      error    syntax error: found character '%' that cannot start any token
24:89     error    line too long (90 > 88 characters)  (line-length)
25:89     error    line too long (167 > 88 characters)  (line-length)
./prometheus/defaults.yaml
6:13      error    too many spaces inside braces  (braces)
6:35      error    too many spaces inside braces  (braces)
7:11      error    too many spaces inside braces  (braces)
7:25      error    too many spaces inside braces …
```
=> feat(yamllint): include for this repo and apply rules throughout

prometheus/config/args/clean.sls, prometheus/config/args/install.sls, prometheus/osfamilymap.yaml, prometheus/service/clean.sls, prometheus/service/running.sls, test/integration/default/controls/environ_spec.rb
This is a mergable solution to the concerns raised in #19.
Tested in Ubuntu 16.04.
=> fix(config): cope with aberrant service names

prometheus/config/args/install.sls, prometheus/defaults.yaml, prometheus/osfamilymap.yaml
Signed-off-by: Mark Gomersbach <markgomersbach@gmail.com>
---
No.
Add values to osfamilymap and a small workaround for Gentoo/openrc configuration style syntax.
=> feat(osfamilymap.yaml): add Gentoo support

prometheus/osfamilymap.yaml, prometheus/package/repo/install.sls
---
No.
The formula has a bad default for Ubuntu because `pkgrepo` does not work. Instead the correct default is `use_upstream_archive: true` on Ubuntu.
Fixes the error:
```
ID: prometheus-package-repo-install-pkgrepo-managed
Function: pkgrepo.managed
Name: prometheus
Result: False
Comment: Failed to configure repo 'prometheus': E: Malformed line 1 in source list /etc/apt/sources.list.d/prometheus.list (type)
E: The list of sources could not be read.
Started: 23:25:10.827838
Duration: 17109.738 ms
Changes:
```
=> fix(ubuntu): pkgrepo cannot be used

prometheus/defaults.yaml, prometheus/service/running.sls
---
No.
#33 
Try to alievate #33 
Firewall formula could be used instead but no harm adding salt ports to default.s.
=> chore(firewall): improve firewalld handling

prometheus/archive/install.sls, prometheus/service/args/clean.sls, prometheus/service/args/install.sls, prometheus/service/running.sls, test/integration/default/controls/archive_spec.rb
---
No.
#36 
#37
Two fixes
- Service.args is only for FreeBSD
- basedir permisisons fixed
=> fix(linux): service.args is freebsd

prometheus/osfamilymap.yaml
---
No.
Gentoo uses it's own go install to compile it's binaries locally.
Also all currently available exporter in Gentoo are added and checked for names.
=> fix(osfamilymap.yaml): add gentoo exporters and remove loose go install

prometheus/defaults.yaml, prometheus/osfamilymap.yaml
---
Yes.
BREAKING CHANGE: The golang clientib is not required for
the regular use of this formula but, if you already expected it to be
installed by default, you'll need to update your pillars to do so.
Running this version of the formula over previous ones won't break the
minions, only skip clientlibs.
This change was discussed (and agreed) in the #formulas channel.
=> fix(defaults): set clientlibs defaults to an empty list

.travis.yml, kitchen.yml, prometheus/defaults.yaml, prometheus/service/running.sls, test/integration/default/controls/service_spec.rb, test/integration/repo/controls/packages_spec.rb, test/integration/repo/controls/service_spec.rb, test/salt/pillar/default.sls, test/salt/pillar/repo.sls
---
No.
Fix https://github.com/saltstack-formulas/prometheus-formula/issues/42
=> Fix node_exporter service not restarted on archive fresh install

prometheus/archive/clean.sls, prometheus/archive/install.sls, prometheus/clientlibs/install.sls, prometheus/config/clean.sls, prometheus/config/environ.sls, prometheus/config/file.sls, prometheus/config/users.sls, prometheus/defaults.yaml, prometheus/exporters/node_exporter/textfile_collectors/init.sls, prometheus/exporters/node_exporter/textfile_collectors/ipmitool/clean.sls, prometheus/exporters/node_exporter/textfile_collectors/ipmitool/init.sls, prometheus/exporters/node_exporter/textfile_collectors/ipmitool/install.sls, prometheus/exporters/node_exporter/textfile_collectors/smartmon/clean.sls, prometheus/exporters/node_exporter/textfile_collectors/smartmon/init.sls, prometheus/exporters/node_exporter/textfile_collectors/smartmon/install.sls, prometheus/osfamilymap.yaml, prometheus/package/repo/clean.sls, prometheus/package/repo/install.sls, prometheus/service/clean.sls, prometheus/service/running.sls
=> chore(windows): basic support

prometheus/defaults.yaml, test/integration/default/controls/archive_spec.rb, test/salt/pillar/default.sls
---
No.
Only updating defaults.yml with latest version form https://prometheus.io/download/
And update test accordingly.
- [] Updated `pillar.example`.
=> Update component to latest versions

prometheus/archive/install.sls, prometheus/clientlibs/install.sls, prometheus/config/file.sls, prometheus/config/users.sls, prometheus/cpuarchmap.yaml, prometheus/exporters/node_exporter/textfile_collectors/init.sls, prometheus/map.jinja, prometheus/service/args/install.sls
---
No.
For Windows OS, Salt has no `osarch` grain so need to use `cpuarch` instead.
Also split `user.present` and `group.present` into separate states per https://github.com/saltstack/salt/issues/58442
=> fix(windows): windows has no osarch grain

prometheus/service/running.sls
---
No.
I noticed a dangling line 44 which should belong to `names` dict.
https://github.com/saltstack-formulas/prometheus-formula/blob/79db2125f7e1869e48f862f661d507d60093747a/prometheus/service/running.sls#L44
=> fix(state): dangling servicename

prometheus/archive/install.sls
---
Feature to use "args" pillar when using archive as upstream
No.
Add already existing "args" value to archive/install.sls:prometheus-archive-install-{{ name }}-managed-service state.
None already existing one
=> Managed args for archive as upstream

pillar.example, prometheus/archive/install.sls, prometheus/map.jinja, test/integration/default/controls/archive_spec.rb, test/salt/pillar/default.sls
---
Support "unofficial" exporter with archive as upstream
No.
Taking care of "unofficial exporter" as postgresql, php-fpm ... 
Under pkg:component:name:archive
adding 
official: true/false ( default => true)
tar: true/false ( default => true)
=> Manage unofficial exporters

prometheus/package/clean.sls
---
No.
The `repo.clean` should probably be included too.
=> fix(clean): include repo clean too

pillar.example, prometheus/archive/install.sls, prometheus/files/default/systemd.ini.jinja, test/integration/default/controls/archive_spec.rb, test/salt/pillar/default.sls
---
Support environment variables for archive exporters as mysqld postgresql ...
No.
Add support  for env variables in systemd unit in archive context
Add array under pkg:component:name:env to manage env vars in systemd
IE in pillar.example
```
mysqld_exporter:
service:
args:
web.listen-address: 0.0.0.0:9192
env:
- 'DATA_SOURCE_NAME=foo:bar@/'
```
=> Manage env vars 

pillar.example, prometheus/archive/install.sls, test/salt/pillar/default.sls
* If a service.args value is define as null, only render the param (key) in the systemd unit file
---
Support command-line arguments without values in archive.install, for example: collector.systemd
No.
Add support for command line options without values in archive.install
Add a key under pkg.component:name.service.args to add command line option to systemd
IE in pillar.example
```
node_exporter:
service:
args:
collector.systemd: null
```
=> feat(archive): allow command line arguments without values in archive.install

prometheus/exporters/node_exporter/textfile_collectors/init.sls
closes #57
---
No.
#57
Fix typo
=> fix(node_exporter): typo

pillar.example, prometheus/config/file.sls, prometheus/defaults.yaml, test/integration/default/controls/archive_spec.rb, test/integration/default/controls/config_spec.rb, test/salt/pillar/default.sls
---
No.
Prometheus configuration use a bunch of extra files (like alerting rules) which were not managed by this formula.
This PR allows to manage those files. A secondary benefit is the possibility to split configuration in multiple files, which is also a common setup.
=> feat(config): allow to manage extra files

prometheus/archive/install.sls
=> fix(indempotency): run reload onchanges only

prometheus/config/users.sls, prometheus/defaults.yaml, prometheus/osfamilymap.yaml
=> fix(defaults): Use nologin instead of /bin/false

prometheus/config/users.sls
---
No.
Missed this in Pull Request #72
=> fix(groups): groups should always be created as system groups

prometheus/config/storage.sls, prometheus/service/args/install.sls
=> fix(storage/install): correct "owner" param to "user"
